function GlobalLicenceStatus() {
	this.status = [{value:80, text:'Active'},
{value:70, text:'Application In Process'},
{value:270, text:'Canceled'},
{value:10, text:'Current License'},
{value:120, text:'Denied'},
{value:130, text:'Expired'},
{value:320, text:'Full'},
{value:30, text:'General Dental License'},
{value:90, text:'Inactive'},
{value:60, text:'Inactive Dental License'},
{value:280, text:'Inactive/Expired'},
{value:140, text:'Lapsed'},
{value:150, text:'Limited'},
{value:260, text:'Other'},
{value:300, text:'Other License'},
{value:160, text:'Pending'},
{value:20, text:'Previous License'},
{value:170, text:'Probation'},
{value:180, text:'Provisional'},
{value:190, text:'Restricted'},
{value:200, text:'Revoked'},
{value:210, text:'Surrendered'},
{value:100, text:'Suspended'},
{value:50, text:'Teacher\'s Dental License'},
{value:220, text:'Temporary'},
{value:230, text:'Terminated'},
{value:240, text:'Time Limited'},
{value:250, text:'Unrestricted'},
{value:110, text:'Worker\'s Compensation'}
];
}